-- ==========================================
-- SEED: Countries
-- ==========================================
-- Reference data from src/backend_lib/shared/data/countries.json (one row per ISO 3166-1 alpha-2).
-- Matches domain validation in countries-dataset.ts / Country value objects.
-- Re-run safe: upserts on iso_code so name and phone_code stay in sync with the JSON source.
-- created_at / updated_at use literal INTERVAL offsets (same style as 001_departments.sql, e.g.
-- NOW() - INTERVAL '90 minutes') so each row has a distinct timestamp for cursor pagination;
-- created_at is NOT overwritten on conflict (stable cursors).
--
-- Note: countries.csv in the repo root is not used here — it contains duplicate iso2 values
-- (historical / legacy rows) which would violate countries.iso_code UNIQUE NOT NULL.

INSERT INTO countries (iso_code, name, phone_code, created_at, updated_at)
VALUES
    ('AC', 'Ascension Island', '+247', NOW() - INTERVAL '0 minutes', NOW() - INTERVAL '0 minutes'),
    ('AD', 'Andorra', '+376', NOW() - INTERVAL '1 minute', NOW() - INTERVAL '1 minute'),
    ('AE', 'United Arab Emirates', '+971', NOW() - INTERVAL '2 minutes', NOW() - INTERVAL '2 minutes'),
    ('AF', 'Afghanistan', '+93', NOW() - INTERVAL '3 minutes', NOW() - INTERVAL '3 minutes'),
    ('AG', 'Antigua And Barbuda', '+1 268', NOW() - INTERVAL '4 minutes', NOW() - INTERVAL '4 minutes'),
    ('AI', 'French Afar and Issas', '', NOW() - INTERVAL '5 minutes', NOW() - INTERVAL '5 minutes'),
    ('AL', 'Albania', '+355', NOW() - INTERVAL '6 minutes', NOW() - INTERVAL '6 minutes'),
    ('AM', 'Armenia', '+374', NOW() - INTERVAL '7 minutes', NOW() - INTERVAL '7 minutes'),
    ('AN', 'Netherlands Antilles', '', NOW() - INTERVAL '8 minutes', NOW() - INTERVAL '8 minutes'),
    ('AO', 'Angola', '+244', NOW() - INTERVAL '9 minutes', NOW() - INTERVAL '9 minutes'),
    ('AQ', 'Antarctica', '+672', NOW() - INTERVAL '10 minutes', NOW() - INTERVAL '10 minutes'),
    ('AR', 'Argentina', '+54', NOW() - INTERVAL '11 minutes', NOW() - INTERVAL '11 minutes'),
    ('AS', 'American Samoa', '+1 684', NOW() - INTERVAL '12 minutes', NOW() - INTERVAL '12 minutes'),
    ('AT', 'Austria', '+43', NOW() - INTERVAL '13 minutes', NOW() - INTERVAL '13 minutes'),
    ('AU', 'Australia', '+61', NOW() - INTERVAL '14 minutes', NOW() - INTERVAL '14 minutes'),
    ('AW', 'Aruba', '+297', NOW() - INTERVAL '15 minutes', NOW() - INTERVAL '15 minutes'),
    ('AX', 'Åland Islands', '+358', NOW() - INTERVAL '16 minutes', NOW() - INTERVAL '16 minutes'),
    ('AZ', 'Azerbaijan', '+994', NOW() - INTERVAL '17 minutes', NOW() - INTERVAL '17 minutes'),
    ('BA', 'Bosnia & Herzegovina', '+387', NOW() - INTERVAL '18 minutes', NOW() - INTERVAL '18 minutes'),
    ('BB', 'Barbados', '+1 246', NOW() - INTERVAL '19 minutes', NOW() - INTERVAL '19 minutes'),
    ('BD', 'Bangladesh', '+880', NOW() - INTERVAL '20 minutes', NOW() - INTERVAL '20 minutes'),
    ('BE', 'Belgium', '+32', NOW() - INTERVAL '21 minutes', NOW() - INTERVAL '21 minutes'),
    ('BF', 'Burkina Faso', '+226', NOW() - INTERVAL '22 minutes', NOW() - INTERVAL '22 minutes'),
    ('BG', 'Bulgaria', '+359', NOW() - INTERVAL '23 minutes', NOW() - INTERVAL '23 minutes'),
    ('BH', 'Bahrain', '+973', NOW() - INTERVAL '24 minutes', NOW() - INTERVAL '24 minutes'),
    ('BI', 'Burundi', '+257', NOW() - INTERVAL '25 minutes', NOW() - INTERVAL '25 minutes'),
    ('BJ', 'Benin', '+229', NOW() - INTERVAL '26 minutes', NOW() - INTERVAL '26 minutes'),
    ('BL', 'Saint Barthélemy', '+590', NOW() - INTERVAL '27 minutes', NOW() - INTERVAL '27 minutes'),
    ('BM', 'Bermuda', '+1 441', NOW() - INTERVAL '28 minutes', NOW() - INTERVAL '28 minutes'),
    ('BN', 'Brunei Darussalam', '+673', NOW() - INTERVAL '29 minutes', NOW() - INTERVAL '29 minutes'),
    ('BO', 'Bolivia, Plurinational State Of', '+591', NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '30 minutes'),
    ('BQ', 'British Antarctic Territory', '', NOW() - INTERVAL '31 minutes', NOW() - INTERVAL '31 minutes'),
    ('BR', 'Brazil', '+55', NOW() - INTERVAL '32 minutes', NOW() - INTERVAL '32 minutes'),
    ('BS', 'Bahamas', '+1 242', NOW() - INTERVAL '33 minutes', NOW() - INTERVAL '33 minutes'),
    ('BT', 'Bhutan', '+975', NOW() - INTERVAL '34 minutes', NOW() - INTERVAL '34 minutes'),
    ('BU', 'Burma', '', NOW() - INTERVAL '35 minutes', NOW() - INTERVAL '35 minutes'),
    ('BV', 'Bouvet Island', '', NOW() - INTERVAL '36 minutes', NOW() - INTERVAL '36 minutes'),
    ('BW', 'Botswana', '+267', NOW() - INTERVAL '37 minutes', NOW() - INTERVAL '37 minutes'),
    ('BY', 'Byelorussian SSR', '', NOW() - INTERVAL '38 minutes', NOW() - INTERVAL '38 minutes'),
    ('BZ', 'Belize', '+501', NOW() - INTERVAL '39 minutes', NOW() - INTERVAL '39 minutes'),
    ('CA', 'Canada', '+1', NOW() - INTERVAL '40 minutes', NOW() - INTERVAL '40 minutes'),
    ('CC', 'Cocos (Keeling) Islands', '+61', NOW() - INTERVAL '41 minutes', NOW() - INTERVAL '41 minutes'),
    ('CD', 'Democratic Republic Of Congo', '+243', NOW() - INTERVAL '42 minutes', NOW() - INTERVAL '42 minutes'),
    ('CF', 'Central African Republic', '+236', NOW() - INTERVAL '43 minutes', NOW() - INTERVAL '43 minutes'),
    ('CG', 'Republic Of Congo', '+242', NOW() - INTERVAL '44 minutes', NOW() - INTERVAL '44 minutes'),
    ('CH', 'Switzerland', '+41', NOW() - INTERVAL '45 minutes', NOW() - INTERVAL '45 minutes'),
    ('CI', 'Côte d''Ivoire', '+225', NOW() - INTERVAL '46 minutes', NOW() - INTERVAL '46 minutes'),
    ('CK', 'Cook Islands', '+682', NOW() - INTERVAL '47 minutes', NOW() - INTERVAL '47 minutes'),
    ('CL', 'Chile', '+56', NOW() - INTERVAL '48 minutes', NOW() - INTERVAL '48 minutes'),
    ('CM', 'Cameroon', '+237', NOW() - INTERVAL '49 minutes', NOW() - INTERVAL '49 minutes'),
    ('CN', 'China', '+86', NOW() - INTERVAL '50 minutes', NOW() - INTERVAL '50 minutes'),
    ('CO', 'Colombia', '+57', NOW() - INTERVAL '51 minutes', NOW() - INTERVAL '51 minutes'),
    ('CP', 'Clipperton Island', '', NOW() - INTERVAL '52 minutes', NOW() - INTERVAL '52 minutes'),
    ('CR', 'Costa Rica', '+506', NOW() - INTERVAL '53 minutes', NOW() - INTERVAL '53 minutes'),
    ('CS', 'Serbia and Montenegro', '', NOW() - INTERVAL '54 minutes', NOW() - INTERVAL '54 minutes'),
    ('CT', 'Canton and Enderbury Islands', '', NOW() - INTERVAL '55 minutes', NOW() - INTERVAL '55 minutes'),
    ('CU', 'Cuba', '+53', NOW() - INTERVAL '56 minutes', NOW() - INTERVAL '56 minutes'),
    ('CV', 'Cabo Verde', '+238', NOW() - INTERVAL '57 minutes', NOW() - INTERVAL '57 minutes'),
    ('CW', 'Curacao', '+599', NOW() - INTERVAL '58 minutes', NOW() - INTERVAL '58 minutes'),
    ('CX', 'Christmas Island', '+61', NOW() - INTERVAL '59 minutes', NOW() - INTERVAL '59 minutes'),
    ('CY', 'Cyprus', '+357', NOW() - INTERVAL '60 minutes', NOW() - INTERVAL '60 minutes'),
    ('CZ', 'Czech Republic', '+420', NOW() - INTERVAL '61 minutes', NOW() - INTERVAL '61 minutes'),
    ('DD', 'German Democratic Republic', '', NOW() - INTERVAL '62 minutes', NOW() - INTERVAL '62 minutes'),
    ('DE', 'Germany', '+49', NOW() - INTERVAL '63 minutes', NOW() - INTERVAL '63 minutes'),
    ('DG', 'Diego Garcia', '', NOW() - INTERVAL '64 minutes', NOW() - INTERVAL '64 minutes'),
    ('DJ', 'Djibouti', '+253', NOW() - INTERVAL '65 minutes', NOW() - INTERVAL '65 minutes'),
    ('DK', 'Denmark', '+45', NOW() - INTERVAL '66 minutes', NOW() - INTERVAL '66 minutes'),
    ('DM', 'Dominica', '+1 767', NOW() - INTERVAL '67 minutes', NOW() - INTERVAL '67 minutes'),
    ('DO', 'Dominican Republic', '+1 809', NOW() - INTERVAL '68 minutes', NOW() - INTERVAL '68 minutes'),
    ('DY', 'Dahomey', '', NOW() - INTERVAL '69 minutes', NOW() - INTERVAL '69 minutes'),
    ('DZ', 'Algeria', '+213', NOW() - INTERVAL '70 minutes', NOW() - INTERVAL '70 minutes'),
    ('EA', 'Ceuta, Mulilla', '', NOW() - INTERVAL '71 minutes', NOW() - INTERVAL '71 minutes'),
    ('EC', 'Ecuador', '+593', NOW() - INTERVAL '72 minutes', NOW() - INTERVAL '72 minutes'),
    ('EE', 'Estonia', '+372', NOW() - INTERVAL '73 minutes', NOW() - INTERVAL '73 minutes'),
    ('EG', 'Egypt', '+20', NOW() - INTERVAL '74 minutes', NOW() - INTERVAL '74 minutes'),
    ('EH', 'Western Sahara', '+212', NOW() - INTERVAL '75 minutes', NOW() - INTERVAL '75 minutes'),
    ('ER', 'Eritrea', '+291', NOW() - INTERVAL '76 minutes', NOW() - INTERVAL '76 minutes'),
    ('ES', 'Spain', '+34', NOW() - INTERVAL '77 minutes', NOW() - INTERVAL '77 minutes'),
    ('ET', 'Ethiopia', '+251', NOW() - INTERVAL '78 minutes', NOW() - INTERVAL '78 minutes'),
    ('EU', 'European Union', '+388', NOW() - INTERVAL '79 minutes', NOW() - INTERVAL '79 minutes'),
    ('FI', 'Finland', '+358', NOW() - INTERVAL '80 minutes', NOW() - INTERVAL '80 minutes'),
    ('FJ', 'Fiji', '+679', NOW() - INTERVAL '81 minutes', NOW() - INTERVAL '81 minutes'),
    ('FK', 'Falkland Islands', '+500', NOW() - INTERVAL '82 minutes', NOW() - INTERVAL '82 minutes'),
    ('FM', 'Micronesia, Federated States Of', '+691', NOW() - INTERVAL '83 minutes', NOW() - INTERVAL '83 minutes'),
    ('FO', 'Faroe Islands', '+298', NOW() - INTERVAL '84 minutes', NOW() - INTERVAL '84 minutes'),
    ('FQ', 'French Southern and Antarctic Territories', '', NOW() - INTERVAL '85 minutes', NOW() - INTERVAL '85 minutes'),
    ('FR', 'France', '+33', NOW() - INTERVAL '86 minutes', NOW() - INTERVAL '86 minutes'),
    ('FX', 'France, Metropolitan', '+241', NOW() - INTERVAL '87 minutes', NOW() - INTERVAL '87 minutes'),
    ('GA', 'Gabon', '+241', NOW() - INTERVAL '88 minutes', NOW() - INTERVAL '88 minutes'),
    ('GB', 'United Kingdom', '+44', NOW() - INTERVAL '89 minutes', NOW() - INTERVAL '89 minutes'),
    ('GD', 'Grenada', '+473', NOW() - INTERVAL '90 minutes', NOW() - INTERVAL '90 minutes'),
    ('GE', 'Gilbert and Ellice Islands', '', NOW() - INTERVAL '91 minutes', NOW() - INTERVAL '91 minutes'),
    ('GF', 'French Guiana', '+594', NOW() - INTERVAL '92 minutes', NOW() - INTERVAL '92 minutes'),
    ('GG', 'Guernsey', '+44', NOW() - INTERVAL '93 minutes', NOW() - INTERVAL '93 minutes'),
    ('GH', 'Ghana', '+233', NOW() - INTERVAL '94 minutes', NOW() - INTERVAL '94 minutes'),
    ('GI', 'Gibraltar', '+350', NOW() - INTERVAL '95 minutes', NOW() - INTERVAL '95 minutes'),
    ('GL', 'Greenland', '+299', NOW() - INTERVAL '96 minutes', NOW() - INTERVAL '96 minutes'),
    ('GM', 'Gambia', '+220', NOW() - INTERVAL '97 minutes', NOW() - INTERVAL '97 minutes'),
    ('GN', 'Guinea', '+224', NOW() - INTERVAL '98 minutes', NOW() - INTERVAL '98 minutes'),
    ('GP', 'Guadeloupe', '+590', NOW() - INTERVAL '99 minutes', NOW() - INTERVAL '99 minutes'),
    ('GQ', 'Equatorial Guinea', '+240', NOW() - INTERVAL '100 minutes', NOW() - INTERVAL '100 minutes'),
    ('GR', 'Greece', '+30', NOW() - INTERVAL '101 minutes', NOW() - INTERVAL '101 minutes'),
    ('GS', 'South Georgia And The South Sandwich Islands', '', NOW() - INTERVAL '102 minutes', NOW() - INTERVAL '102 minutes'),
    ('GT', 'Guatemala', '+502', NOW() - INTERVAL '103 minutes', NOW() - INTERVAL '103 minutes'),
    ('GU', 'Guam', '+1 671', NOW() - INTERVAL '104 minutes', NOW() - INTERVAL '104 minutes'),
    ('GW', 'Guinea-bissau', '+245', NOW() - INTERVAL '105 minutes', NOW() - INTERVAL '105 minutes'),
    ('GY', 'Guyana', '+592', NOW() - INTERVAL '106 minutes', NOW() - INTERVAL '106 minutes'),
    ('HK', 'Hong Kong', '+852', NOW() - INTERVAL '107 minutes', NOW() - INTERVAL '107 minutes'),
    ('HM', 'Heard Island And McDonald Islands', '', NOW() - INTERVAL '108 minutes', NOW() - INTERVAL '108 minutes'),
    ('HN', 'Honduras', '+504', NOW() - INTERVAL '109 minutes', NOW() - INTERVAL '109 minutes'),
    ('HR', 'Croatia', '+385', NOW() - INTERVAL '110 minutes', NOW() - INTERVAL '110 minutes'),
    ('HT', 'Haiti', '+509', NOW() - INTERVAL '111 minutes', NOW() - INTERVAL '111 minutes'),
    ('HU', 'Hungary', '+36', NOW() - INTERVAL '112 minutes', NOW() - INTERVAL '112 minutes'),
    ('HV', 'Upper Volta', '', NOW() - INTERVAL '113 minutes', NOW() - INTERVAL '113 minutes'),
    ('IC', 'Canary Islands', '', NOW() - INTERVAL '114 minutes', NOW() - INTERVAL '114 minutes'),
    ('ID', 'Indonesia', '+62', NOW() - INTERVAL '115 minutes', NOW() - INTERVAL '115 minutes'),
    ('IE', 'Ireland', '+353', NOW() - INTERVAL '116 minutes', NOW() - INTERVAL '116 minutes'),
    ('IL', 'Israel', '+972', NOW() - INTERVAL '117 minutes', NOW() - INTERVAL '117 minutes'),
    ('IM', 'Isle Of Man', '+44', NOW() - INTERVAL '118 minutes', NOW() - INTERVAL '118 minutes'),
    ('IN', 'India', '+91', NOW() - INTERVAL '119 minutes', NOW() - INTERVAL '119 minutes'),
    ('IO', 'British Indian Ocean Territory', '+246', NOW() - INTERVAL '120 minutes', NOW() - INTERVAL '120 minutes'),
    ('IQ', 'Iraq', '+964', NOW() - INTERVAL '121 minutes', NOW() - INTERVAL '121 minutes'),
    ('IR', 'Iran, Islamic Republic Of', '+98', NOW() - INTERVAL '122 minutes', NOW() - INTERVAL '122 minutes'),
    ('IS', 'Iceland', '+354', NOW() - INTERVAL '123 minutes', NOW() - INTERVAL '123 minutes'),
    ('IT', 'Italy', '+39', NOW() - INTERVAL '124 minutes', NOW() - INTERVAL '124 minutes'),
    ('JE', 'Jersey', '+44', NOW() - INTERVAL '125 minutes', NOW() - INTERVAL '125 minutes'),
    ('JM', 'Jamaica', '+1 876', NOW() - INTERVAL '126 minutes', NOW() - INTERVAL '126 minutes'),
    ('JO', 'Jordan', '+962', NOW() - INTERVAL '127 minutes', NOW() - INTERVAL '127 minutes'),
    ('JP', 'Japan', '+81', NOW() - INTERVAL '128 minutes', NOW() - INTERVAL '128 minutes'),
    ('JT', 'Johnston Island', '', NOW() - INTERVAL '129 minutes', NOW() - INTERVAL '129 minutes'),
    ('KE', 'Kenya', '+254', NOW() - INTERVAL '130 minutes', NOW() - INTERVAL '130 minutes'),
    ('KG', 'Kyrgyzstan', '+996', NOW() - INTERVAL '131 minutes', NOW() - INTERVAL '131 minutes'),
    ('KH', 'Cambodia', '+855', NOW() - INTERVAL '132 minutes', NOW() - INTERVAL '132 minutes'),
    ('KI', 'Kiribati', '+686', NOW() - INTERVAL '133 minutes', NOW() - INTERVAL '133 minutes'),
    ('KM', 'Comoros', '+269', NOW() - INTERVAL '134 minutes', NOW() - INTERVAL '134 minutes'),
    ('KN', 'Saint Kitts And Nevis', '+1 869', NOW() - INTERVAL '135 minutes', NOW() - INTERVAL '135 minutes'),
    ('KP', 'Korea, Democratic People''s Republic Of', '+850', NOW() - INTERVAL '136 minutes', NOW() - INTERVAL '136 minutes'),
    ('KR', 'Korea, Republic Of', '+82', NOW() - INTERVAL '137 minutes', NOW() - INTERVAL '137 minutes'),
    ('KW', 'Kuwait', '+965', NOW() - INTERVAL '138 minutes', NOW() - INTERVAL '138 minutes'),
    ('KY', 'Cayman Islands', '+1 345', NOW() - INTERVAL '139 minutes', NOW() - INTERVAL '139 minutes'),
    ('KZ', 'Kazakhstan', '+7', NOW() - INTERVAL '140 minutes', NOW() - INTERVAL '140 minutes'),
    ('LA', 'Lao People''s Democratic Republic', '+856', NOW() - INTERVAL '141 minutes', NOW() - INTERVAL '141 minutes'),
    ('LB', 'Lebanon', '+961', NOW() - INTERVAL '142 minutes', NOW() - INTERVAL '142 minutes'),
    ('LC', 'Saint Lucia', '+1 758', NOW() - INTERVAL '143 minutes', NOW() - INTERVAL '143 minutes'),
    ('LI', 'Liechtenstein', '+423', NOW() - INTERVAL '144 minutes', NOW() - INTERVAL '144 minutes'),
    ('LK', 'Sri Lanka', '+94', NOW() - INTERVAL '145 minutes', NOW() - INTERVAL '145 minutes'),
    ('LR', 'Liberia', '+231', NOW() - INTERVAL '146 minutes', NOW() - INTERVAL '146 minutes'),
    ('LS', 'Lesotho', '+266', NOW() - INTERVAL '147 minutes', NOW() - INTERVAL '147 minutes'),
    ('LT', 'Lithuania', '+370', NOW() - INTERVAL '148 minutes', NOW() - INTERVAL '148 minutes'),
    ('LU', 'Luxembourg', '+352', NOW() - INTERVAL '149 minutes', NOW() - INTERVAL '149 minutes'),
    ('LV', 'Latvia', '+371', NOW() - INTERVAL '150 minutes', NOW() - INTERVAL '150 minutes'),
    ('LY', 'Libya', '+218', NOW() - INTERVAL '151 minutes', NOW() - INTERVAL '151 minutes'),
    ('MA', 'Morocco', '+212', NOW() - INTERVAL '152 minutes', NOW() - INTERVAL '152 minutes'),
    ('MC', 'Monaco', '+377', NOW() - INTERVAL '153 minutes', NOW() - INTERVAL '153 minutes'),
    ('MD', 'Moldova', '+373', NOW() - INTERVAL '154 minutes', NOW() - INTERVAL '154 minutes'),
    ('ME', 'Montenegro', '+382', NOW() - INTERVAL '155 minutes', NOW() - INTERVAL '155 minutes'),
    ('MF', 'Saint Martin', '+590', NOW() - INTERVAL '156 minutes', NOW() - INTERVAL '156 minutes'),
    ('MG', 'Madagascar', '+261', NOW() - INTERVAL '157 minutes', NOW() - INTERVAL '157 minutes'),
    ('MH', 'Marshall Islands', '+692', NOW() - INTERVAL '158 minutes', NOW() - INTERVAL '158 minutes'),
    ('MI', 'Midway Islands', '', NOW() - INTERVAL '159 minutes', NOW() - INTERVAL '159 minutes'),
    ('MK', 'Macedonia, The Former Yugoslav Republic Of', '+389', NOW() - INTERVAL '160 minutes', NOW() - INTERVAL '160 minutes'),
    ('ML', 'Mali', '+223', NOW() - INTERVAL '161 minutes', NOW() - INTERVAL '161 minutes'),
    ('MM', 'Myanmar', '+95', NOW() - INTERVAL '162 minutes', NOW() - INTERVAL '162 minutes'),
    ('MN', 'Mongolia', '+976', NOW() - INTERVAL '163 minutes', NOW() - INTERVAL '163 minutes'),
    ('MO', 'Macao', '+853', NOW() - INTERVAL '164 minutes', NOW() - INTERVAL '164 minutes'),
    ('MP', 'Northern Mariana Islands', '+1 670', NOW() - INTERVAL '165 minutes', NOW() - INTERVAL '165 minutes'),
    ('MQ', 'Martinique', '+596', NOW() - INTERVAL '166 minutes', NOW() - INTERVAL '166 minutes'),
    ('MR', 'Mauritania', '+222', NOW() - INTERVAL '167 minutes', NOW() - INTERVAL '167 minutes'),
    ('MS', 'Montserrat', '+1 664', NOW() - INTERVAL '168 minutes', NOW() - INTERVAL '168 minutes'),
    ('MT', 'Malta', '+356', NOW() - INTERVAL '169 minutes', NOW() - INTERVAL '169 minutes'),
    ('MU', 'Mauritius', '+230', NOW() - INTERVAL '170 minutes', NOW() - INTERVAL '170 minutes'),
    ('MV', 'Maldives', '+960', NOW() - INTERVAL '171 minutes', NOW() - INTERVAL '171 minutes'),
    ('MW', 'Malawi', '+265', NOW() - INTERVAL '172 minutes', NOW() - INTERVAL '172 minutes'),
    ('MX', 'Mexico', '+52', NOW() - INTERVAL '173 minutes', NOW() - INTERVAL '173 minutes'),
    ('MY', 'Malaysia', '+60', NOW() - INTERVAL '174 minutes', NOW() - INTERVAL '174 minutes'),
    ('MZ', 'Mozambique', '+258', NOW() - INTERVAL '175 minutes', NOW() - INTERVAL '175 minutes'),
    ('NA', 'Namibia', '+264', NOW() - INTERVAL '176 minutes', NOW() - INTERVAL '176 minutes'),
    ('NC', 'New Caledonia', '+687', NOW() - INTERVAL '177 minutes', NOW() - INTERVAL '177 minutes'),
    ('NE', 'Niger', '+227', NOW() - INTERVAL '178 minutes', NOW() - INTERVAL '178 minutes'),
    ('NF', 'Norfolk Island', '+672', NOW() - INTERVAL '179 minutes', NOW() - INTERVAL '179 minutes'),
    ('NG', 'Nigeria', '+234', NOW() - INTERVAL '180 minutes', NOW() - INTERVAL '180 minutes'),
    ('NH', 'New Hebrides', '', NOW() - INTERVAL '181 minutes', NOW() - INTERVAL '181 minutes'),
    ('NI', 'Nicaragua', '+505', NOW() - INTERVAL '182 minutes', NOW() - INTERVAL '182 minutes'),
    ('NL', 'Netherlands', '+31', NOW() - INTERVAL '183 minutes', NOW() - INTERVAL '183 minutes'),
    ('NO', 'Norway', '+47', NOW() - INTERVAL '184 minutes', NOW() - INTERVAL '184 minutes'),
    ('NP', 'Nepal', '+977', NOW() - INTERVAL '185 minutes', NOW() - INTERVAL '185 minutes'),
    ('NQ', 'Dronning Maud Land', '', NOW() - INTERVAL '186 minutes', NOW() - INTERVAL '186 minutes'),
    ('NR', 'Nauru', '+674', NOW() - INTERVAL '187 minutes', NOW() - INTERVAL '187 minutes'),
    ('NT', 'Neutral Zone', '', NOW() - INTERVAL '188 minutes', NOW() - INTERVAL '188 minutes'),
    ('NU', 'Niue', '+683', NOW() - INTERVAL '189 minutes', NOW() - INTERVAL '189 minutes'),
    ('NZ', 'New Zealand', '+64', NOW() - INTERVAL '190 minutes', NOW() - INTERVAL '190 minutes'),
    ('OM', 'Oman', '+968', NOW() - INTERVAL '191 minutes', NOW() - INTERVAL '191 minutes'),
    ('PA', 'Panama', '+507', NOW() - INTERVAL '192 minutes', NOW() - INTERVAL '192 minutes'),
    ('PC', 'Pacific Islands, Trust Territory of the', '', NOW() - INTERVAL '193 minutes', NOW() - INTERVAL '193 minutes'),
    ('PE', 'Peru', '+51', NOW() - INTERVAL '194 minutes', NOW() - INTERVAL '194 minutes'),
    ('PF', 'French Polynesia', '+689', NOW() - INTERVAL '195 minutes', NOW() - INTERVAL '195 minutes'),
    ('PG', 'Papua New Guinea', '+675', NOW() - INTERVAL '196 minutes', NOW() - INTERVAL '196 minutes'),
    ('PH', 'Philippines', '+63', NOW() - INTERVAL '197 minutes', NOW() - INTERVAL '197 minutes'),
    ('PK', 'Pakistan', '+92', NOW() - INTERVAL '198 minutes', NOW() - INTERVAL '198 minutes'),
    ('PL', 'Poland', '+48', NOW() - INTERVAL '199 minutes', NOW() - INTERVAL '199 minutes'),
    ('PM', 'Saint Pierre And Miquelon', '+508', NOW() - INTERVAL '200 minutes', NOW() - INTERVAL '200 minutes'),
    ('PN', 'Pitcairn', '+872', NOW() - INTERVAL '201 minutes', NOW() - INTERVAL '201 minutes'),
    ('PR', 'Puerto Rico', '+1 787', NOW() - INTERVAL '202 minutes', NOW() - INTERVAL '202 minutes'),
    ('PS', 'Palestinian Territory, Occupied', '+970', NOW() - INTERVAL '203 minutes', NOW() - INTERVAL '203 minutes'),
    ('PT', 'Portugal', '+351', NOW() - INTERVAL '204 minutes', NOW() - INTERVAL '204 minutes'),
    ('PU', 'U.S. Miscellaneous Pacific Islands', '', NOW() - INTERVAL '205 minutes', NOW() - INTERVAL '205 minutes'),
    ('PW', 'Palau', '+680', NOW() - INTERVAL '206 minutes', NOW() - INTERVAL '206 minutes'),
    ('PY', 'Paraguay', '+595', NOW() - INTERVAL '207 minutes', NOW() - INTERVAL '207 minutes'),
    ('PZ', 'Panama Canal Zone', '', NOW() - INTERVAL '208 minutes', NOW() - INTERVAL '208 minutes'),
    ('QA', 'Qatar', '+974', NOW() - INTERVAL '209 minutes', NOW() - INTERVAL '209 minutes'),
    ('RE', 'Reunion', '+262', NOW() - INTERVAL '210 minutes', NOW() - INTERVAL '210 minutes'),
    ('RH', 'Southern Rhodesia', '', NOW() - INTERVAL '211 minutes', NOW() - INTERVAL '211 minutes'),
    ('RO', 'Romania', '+40', NOW() - INTERVAL '212 minutes', NOW() - INTERVAL '212 minutes'),
    ('RS', 'Serbia', '+381', NOW() - INTERVAL '213 minutes', NOW() - INTERVAL '213 minutes'),
    ('RU', 'Russian Federation', '+7', NOW() - INTERVAL '214 minutes', NOW() - INTERVAL '214 minutes'),
    ('RW', 'Rwanda', '+250', NOW() - INTERVAL '215 minutes', NOW() - INTERVAL '215 minutes'),
    ('SA', 'Saudi Arabia', '+966', NOW() - INTERVAL '216 minutes', NOW() - INTERVAL '216 minutes'),
    ('SB', 'Solomon Islands', '+677', NOW() - INTERVAL '217 minutes', NOW() - INTERVAL '217 minutes'),
    ('SC', 'Seychelles', '+248', NOW() - INTERVAL '218 minutes', NOW() - INTERVAL '218 minutes'),
    ('SD', 'Sudan', '+249', NOW() - INTERVAL '219 minutes', NOW() - INTERVAL '219 minutes'),
    ('SE', 'Sweden', '+46', NOW() - INTERVAL '220 minutes', NOW() - INTERVAL '220 minutes'),
    ('SG', 'Singapore', '+65', NOW() - INTERVAL '221 minutes', NOW() - INTERVAL '221 minutes'),
    ('SH', 'Saint Helena, Ascension And Tristan Da Cunha', '+290', NOW() - INTERVAL '222 minutes', NOW() - INTERVAL '222 minutes'),
    ('SI', 'Slovenia', '+386', NOW() - INTERVAL '223 minutes', NOW() - INTERVAL '223 minutes'),
    ('SJ', 'Svalbard And Jan Mayen', '+47', NOW() - INTERVAL '224 minutes', NOW() - INTERVAL '224 minutes'),
    ('SK', 'Sikkim', '', NOW() - INTERVAL '225 minutes', NOW() - INTERVAL '225 minutes'),
    ('SL', 'Sierra Leone', '+232', NOW() - INTERVAL '226 minutes', NOW() - INTERVAL '226 minutes'),
    ('SM', 'San Marino', '+378', NOW() - INTERVAL '227 minutes', NOW() - INTERVAL '227 minutes'),
    ('SN', 'Senegal', '+221', NOW() - INTERVAL '228 minutes', NOW() - INTERVAL '228 minutes'),
    ('SO', 'Somalia', '+252', NOW() - INTERVAL '229 minutes', NOW() - INTERVAL '229 minutes'),
    ('SR', 'Suriname', '+597', NOW() - INTERVAL '230 minutes', NOW() - INTERVAL '230 minutes'),
    ('SS', 'South Sudan', '+211', NOW() - INTERVAL '231 minutes', NOW() - INTERVAL '231 minutes'),
    ('ST', 'Sao Tome and Principe', '+239', NOW() - INTERVAL '232 minutes', NOW() - INTERVAL '232 minutes'),
    ('SU', 'USSR', '', NOW() - INTERVAL '233 minutes', NOW() - INTERVAL '233 minutes'),
    ('SV', 'El Salvador', '+503', NOW() - INTERVAL '234 minutes', NOW() - INTERVAL '234 minutes'),
    ('SX', 'Sint Maarten', '+1 721', NOW() - INTERVAL '235 minutes', NOW() - INTERVAL '235 minutes'),
    ('SY', 'Syrian Arab Republic', '+963', NOW() - INTERVAL '236 minutes', NOW() - INTERVAL '236 minutes'),
    ('SZ', 'Swaziland', '+268', NOW() - INTERVAL '237 minutes', NOW() - INTERVAL '237 minutes'),
    ('TA', 'Tristan de Cunha', '+290', NOW() - INTERVAL '238 minutes', NOW() - INTERVAL '238 minutes'),
    ('TC', 'Turks And Caicos Islands', '+1 649', NOW() - INTERVAL '239 minutes', NOW() - INTERVAL '239 minutes'),
    ('TD', 'Chad', '+235', NOW() - INTERVAL '240 minutes', NOW() - INTERVAL '240 minutes'),
    ('TF', 'French Southern Territories', '', NOW() - INTERVAL '241 minutes', NOW() - INTERVAL '241 minutes'),
    ('TG', 'Togo', '+228', NOW() - INTERVAL '242 minutes', NOW() - INTERVAL '242 minutes'),
    ('TH', 'Thailand', '+66', NOW() - INTERVAL '243 minutes', NOW() - INTERVAL '243 minutes'),
    ('TJ', 'Tajikistan', '+992', NOW() - INTERVAL '244 minutes', NOW() - INTERVAL '244 minutes'),
    ('TK', 'Tokelau', '+690', NOW() - INTERVAL '245 minutes', NOW() - INTERVAL '245 minutes'),
    ('TL', 'Timor-Leste, Democratic Republic of', '+670', NOW() - INTERVAL '246 minutes', NOW() - INTERVAL '246 minutes'),
    ('TM', 'Turkmenistan', '+993', NOW() - INTERVAL '247 minutes', NOW() - INTERVAL '247 minutes'),
    ('TN', 'Tunisia', '+216', NOW() - INTERVAL '248 minutes', NOW() - INTERVAL '248 minutes'),
    ('TO', 'Tonga', '+676', NOW() - INTERVAL '249 minutes', NOW() - INTERVAL '249 minutes'),
    ('TP', 'East Timor', '', NOW() - INTERVAL '250 minutes', NOW() - INTERVAL '250 minutes'),
    ('TR', 'Turkey', '+90', NOW() - INTERVAL '251 minutes', NOW() - INTERVAL '251 minutes'),
    ('TT', 'Trinidad And Tobago', '+1 868', NOW() - INTERVAL '252 minutes', NOW() - INTERVAL '252 minutes'),
    ('TV', 'Tuvalu', '+688', NOW() - INTERVAL '253 minutes', NOW() - INTERVAL '253 minutes'),
    ('TW', 'Taiwan', '+886', NOW() - INTERVAL '254 minutes', NOW() - INTERVAL '254 minutes'),
    ('TZ', 'Tanzania, United Republic Of', '+255', NOW() - INTERVAL '255 minutes', NOW() - INTERVAL '255 minutes'),
    ('UA', 'Ukraine', '+380', NOW() - INTERVAL '256 minutes', NOW() - INTERVAL '256 minutes'),
    ('UG', 'Uganda', '+256', NOW() - INTERVAL '257 minutes', NOW() - INTERVAL '257 minutes'),
    ('UK', 'United Kingdom', '', NOW() - INTERVAL '258 minutes', NOW() - INTERVAL '258 minutes'),
    ('UM', 'United States Minor Outlying Islands', '+1', NOW() - INTERVAL '259 minutes', NOW() - INTERVAL '259 minutes'),
    ('US', 'United States', '+1', NOW() - INTERVAL '260 minutes', NOW() - INTERVAL '260 minutes'),
    ('UY', 'Uruguay', '+598', NOW() - INTERVAL '261 minutes', NOW() - INTERVAL '261 minutes'),
    ('UZ', 'Uzbekistan', '+998', NOW() - INTERVAL '262 minutes', NOW() - INTERVAL '262 minutes'),
    ('VA', 'Vatican City State', '+379', NOW() - INTERVAL '263 minutes', NOW() - INTERVAL '263 minutes'),
    ('VC', 'Saint Vincent And The Grenadines', '+1 784', NOW() - INTERVAL '264 minutes', NOW() - INTERVAL '264 minutes'),
    ('VD', 'Viet-Nam, Democratic Republic of', '', NOW() - INTERVAL '265 minutes', NOW() - INTERVAL '265 minutes'),
    ('VE', 'Venezuela, Bolivarian Republic Of', '+58', NOW() - INTERVAL '266 minutes', NOW() - INTERVAL '266 minutes'),
    ('VG', 'Virgin Islands (British)', '+1 284', NOW() - INTERVAL '267 minutes', NOW() - INTERVAL '267 minutes'),
    ('VI', 'Virgin Islands (US)', '+1 340', NOW() - INTERVAL '268 minutes', NOW() - INTERVAL '268 minutes'),
    ('VN', 'Viet Nam', '+84', NOW() - INTERVAL '269 minutes', NOW() - INTERVAL '269 minutes'),
    ('VU', 'Vanuatu', '+678', NOW() - INTERVAL '270 minutes', NOW() - INTERVAL '270 minutes'),
    ('WF', 'Wallis And Futuna', '+681', NOW() - INTERVAL '271 minutes', NOW() - INTERVAL '271 minutes'),
    ('WK', 'Wake Island', '', NOW() - INTERVAL '272 minutes', NOW() - INTERVAL '272 minutes'),
    ('WS', 'Samoa', '+685', NOW() - INTERVAL '273 minutes', NOW() - INTERVAL '273 minutes'),
    ('XK', 'Kosovo', '+383', NOW() - INTERVAL '274 minutes', NOW() - INTERVAL '274 minutes'),
    ('YD', 'Yemen, Democratic', '', NOW() - INTERVAL '275 minutes', NOW() - INTERVAL '275 minutes'),
    ('YE', 'Yemen', '+967', NOW() - INTERVAL '276 minutes', NOW() - INTERVAL '276 minutes'),
    ('YT', 'Mayotte', '+262', NOW() - INTERVAL '277 minutes', NOW() - INTERVAL '277 minutes'),
    ('YU', 'Yugoslavia', '', NOW() - INTERVAL '278 minutes', NOW() - INTERVAL '278 minutes'),
    ('ZA', 'South Africa', '+27', NOW() - INTERVAL '279 minutes', NOW() - INTERVAL '279 minutes'),
    ('ZM', 'Zambia', '+260', NOW() - INTERVAL '280 minutes', NOW() - INTERVAL '280 minutes'),
    ('ZR', 'Zaire', '', NOW() - INTERVAL '281 minutes', NOW() - INTERVAL '281 minutes'),
    ('ZW', 'Zimbabwe', '+263', NOW() - INTERVAL '282 minutes', NOW() - INTERVAL '282 minutes')
ON CONFLICT (iso_code) DO UPDATE SET
    name = EXCLUDED.name,
    phone_code = EXCLUDED.phone_code,
    updated_at = NOW();
